version: '3'

services:
  mkdocs:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /var/www/mkdocs/site/www.web-my-dev.fr:/docs
      - /var/www/mkdocs/site/Markdown:/docs/Markdown
      - "./overrides:/docs/overrides"

