# Workflow actions
name: Workflow CD

on:
  # Trigger push on branch
  push:
    branches: [ main ]

jobs:
  build:
    # Type of runner
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/mkdocs/site/www.web-my-dev.fr
            git pull
            docker-compose down
            docker-compose up -d
